     Info:  Nimble data file "/home/runner/.nimble/nimbledata2.json" has been loaded.
    Reading official package list
Downloading https://github.com/jaredmontoya/pyopenai using git
    Cloning latest tagged version: 0.2.0
open('/workspace/destdir/ssl/openssl.cnf', 32768, 0x00000000000001b6)
open('/home/runner/.config/nimble/nimble.ini', 557056, 0x00000000000001b6)
open('/home/runner/.config/babel/babel.ini', 557056, 0x00000000000001b6)
open('/home/runner/.nimble/nimbledata2.json', 557056, 0x00000000000001b6)
writev(1, 0x00007fff627ad0e0, 2)
writev(1, 0x00007fff627ac9c0, 2)
open('/home/runner/.nimble/packages_official.json', 557056, 0x00000000000001b6)
mkdir('/tmp/', 0x00000000000001ff)
mkdir('/tmp/nimble_3907/', 0x00000000000001ff)
mkdir('/tmp/nimble_3907/githubcom_jaredmontoyapyopenai', 0x00000000000001ff)
writev(1, 0x00007fff627ac990, 2)
open('/tmp/nimble_3907/githubcom_jaredmontoyapyopenai', 622592, 0x0000000000000000)
rmdir('/tmp/nimble_3907/githubcom_jaredmontoyapyopenai')
writev(1, 0x00007fff627ac900, 2)
mkdir(94493591139696, 0x00000000000001ff)
Error tracing process: readBytes(0x000055f100eef570, 256) error: [Errno 5] Input/output error.
